// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QtjN7pIgbsX38wPCI3u0vRueS7j23dI',
    appId: '1:621155471284:web:31f6d8fc65b3cea81a2ce1',
    messagingSenderId: '621155471284',
    projectId: 'device-streaming-22d3820a',
    authDomain: 'device-streaming-22d3820a.firebaseapp.com',
    storageBucket: 'device-streaming-22d3820a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7hOclYtB_-g7Wnc86mZ9Yr8KjBKt36E',
    appId: '1:621155471284:ios:faf536138539f9b71a2ce1',
    messagingSenderId: '621155471284',
    projectId: 'device-streaming-22d3820a',
    storageBucket: 'device-streaming-22d3820a.firebasestorage.app',
    iosBundleId: 'com.example.coursePath',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7hOclYtB_-g7Wnc86mZ9Yr8KjBKt36E',
    appId: '1:621155471284:ios:faf536138539f9b71a2ce1',
    messagingSenderId: '621155471284',
    projectId: 'device-streaming-22d3820a',
    storageBucket: 'device-streaming-22d3820a.firebasestorage.app',
    iosBundleId: 'com.example.coursePath',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbjwkvfalNnMRoRHFBo1cX5qgxVMiwJ8o',
    appId: '1:621155471284:android:5d2a126959e85fcc1a2ce1',
    messagingSenderId: '621155471284',
    projectId: 'device-streaming-22d3820a',
    storageBucket: 'device-streaming-22d3820a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2QtjN7pIgbsX38wPCI3u0vRueS7j23dI',
    appId: '1:621155471284:web:6a714f5f009416ca1a2ce1',
    messagingSenderId: '621155471284',
    projectId: 'device-streaming-22d3820a',
    authDomain: 'device-streaming-22d3820a.firebaseapp.com',
    storageBucket: 'device-streaming-22d3820a.firebasestorage.app',
  );

}